@authUrl=http://localhost:3000/nodejs_api/user/login
@postBase=http://localhost:3000/nodejs_api/post
@base=http://localhost:3000/nodejs_api

# @name loginAPI
## 登录拿token
POST {{base}}/user/login
Content-Type: application/json

{
    "password": "123456",
    "email": "123456@qq.com"
}
### 获取token
@token = {{loginAPI.response.body.&.data}}
@msg = {{loginAPI.request.body.$.email}}
# @token={{response.body.$.data.data}}
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsInVzZXJuYW1lIjpudWxsLCJpYXQiOjE3NjgzNjY0NjZ9.rKGTs5qU3t9WegL1ptLwbbwcAHTmPtuJxwF1ncAPkJA


### 获取文章列表
GET {{postBase}}?cookie={{msg}}
Authorization: {{token}}
# GET {{userBase}}/query?name=john

# ### userLogin
# POST {{userBase}}/login
# Content-Type: application/json

# {
#     "username": "admin",
#     "password": "123456"
# }

# ###  userRegister
# POST {{userBase}}/register
# Content-Type: application/json

# {
#     "email": "admin99@163.com",
#     "password": "123456"
# }

# ### jwt test
# GET http://localhost:3000/sign/mike