@authUrl=http://localhost:3000/api/user/login
@postBase=http://localhost:3000/api/post
@base=http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsInVzZXJuYW1lIjpudWxsLCJpYXQiOjE3NjgzNjUzMjN9.xgLCMTF7CAKCpgb83FqBuWZ9OaqVv9-t_wwRVCESBSU

## 登录拿token
# @name loginAPI
POST {{base}}/user/login
Content-Type: application/json

{
    "password": "123456",
    "email": "123456@qq.com"
}


### 获取文章列表
GET {{postBase}}?cookie=test
Authorization: {{token}}
### userList
# GET {{userBase}}/query?name=john

# ### userLogin
# POST {{userBase}}/login
# Content-Type: application/json

# {
#     "username": "admin",
#     "password": "123456"
# }

# ###  userRegister
# POST {{userBase}}/register
# Content-Type: application/json

# {
#     "email": "admin99@163.com",
#     "password": "123456"
# }

# ### jwt test
# GET http://localhost:3000/sign/mike