@base=http://localhost:3000/api/product
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjpudWxsLCJpYXQiOjE3NjkwNDc1OTB9.N11s-GuBoWAG7Tnys4PkndiUH9c5KnrM47dUS9OBZpI
### user list
GET {{base}}
Authorization: {{token}}
### create product
POST {{base}}
Content-Type: application/json

{
    "name": "beer445",
    "vendorId": 3,
    "shelfPrice": 100
}


### 根据id获取产品
GET {{base}}/getProductById/3