@base=http://localhost:3000/api/stockin
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiI0MTMxMTQ0QHFxLmNvbSIsInVzZXJuYW1lIjoibWlrMTEyIiwiYXZhdGFyIjoiMTIzMTIiLCJjcmVhdGVBdCI6IjIwMjUtMDEtMjVUMDU6MjM6NDcuNDU4WiIsInVwZGF0ZUF0IjoiMjAyNS0wMi0wMlQyMzowOTo1Ny4wMjVaIiwiaWF0IjoxNzM4NTUwOTAyLCJleHAiOjE3Mzg2MzczMDJ9.jPCKGmaEOLe-JrITR8-whbYfoS3r-Xf1y8JOVVrCOK4

### user list
GET {{base}}?limit=10&page=1
Authorization: Bearer {{token}}

### create import
POST {{base}}/single
Content-Type: application/json

{
    "remark": "importRemark",
    "cost": 10, 
    "count": 20,
    "productId": 5
}

### create import
POST {{base}}/multiple
Content-Type: application/json

{
    "remark": "importRemark",
    "productJoinStockIn": [
        {
            "cost": 100, 
            "count": 200,
            "productId": 3
        },
        {
            "cost": 10, 
            "count": 20,
            "productId": 4
        }
    ]
}

### update stockIn
PUT {{base}}/2
Content-Type: application/json

{
    "remark": "importRemark",
    "productJoinStockIn": [
        {
            "cost": 19, 
            "count": 40,
            "productId": 1
        },
        {
            "cost": 200, 
            "count": 300,
            "productId": 2
        }
    ]
}
