@base=http://localhost:3000/api/stockout
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiI0MTMxMTQ0QHFxLmNvbSIsInVzZXJuYW1lIjoibWlrMTEyIiwiYXZhdGFyIjoiMTIzMTIiLCJjcmVhdGVBdCI6IjIwMjUtMDEtMjVUMDU6MjM6NDcuNDU4WiIsInVwZGF0ZUF0IjoiMjAyNS0wMi0wMlQyMzowOTo1Ny4wMjVaIiwiaWF0IjoxNzM4NTUwOTAyLCJleHAiOjE3Mzg2MzczMDJ9.jPCKGmaEOLe-JrITR8-whbYfoS3r-Xf1y8JOVVrCOK4

### user list
GET {{base}}?limit=10&page=1
Authorization: Bearer {{token}}

### create stockOut
POST {{base}}/multiple
Content-Type: application/json

{
    "remark": "good",
    "productJoinStockOut": [
        {
            "price": 10, 
            "count": 2,
            "productId": 2
        }
    ]
}