@base=http://localhost:3000/nodejs_api/stockin
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWFjaGVuMjAxMkBvdXRsb29rLmNvbSIsImlhdCI6MTc3MDAyNjUzOH0.vX_3XViZeOJQGRXpDdEinzeWe9AVTZJHuyEGp-CNW1I

### stockIn list
GET {{base}}?productName=puma&deletedStart=2025-11-12&deletedEnd=2026-03-02
Authorization: Bearer {{token}}

### create import
POST {{base}}/single
Content-Type: application/json

{
    "remark": "importRemark",
    "cost": 10, 
    "count": 20,
    "productId": 5
}

### create import
POST {{base}}/multiple
Content-Type: application/json
Authorization: {{token}}

{
    "remark": "importRemark",
    "productJoinStockIn": [
        {
            "cost": 100, 
            "count": 200,
            "productId": 1,
            "shelfPrice":1,
            "vendorId": 1
        },
        {
            "cost": 10, 
            "count": 20,
            "productId": 1,
            "shelfPrice":10,
            "vendorId": 1
        }
    ]
}

### update stockIn
PUT {{base}}/13
Content-Type: application/json
Authorization: {{token}}

{
    "remark": "importRemark",
    "productJoinStockIn": [
        {
            "cost": 19, 
            "count": 40,
            "productId": 1,
            "vendorId": 1,
            "shelfPrice": 10
        },
        {
            "cost": 200, 
            "count": 300,
            "productId": 2,
            "vendorId": 1,
            "shelfPrice": 10
        }
    ]
}

### 删除进货单
DELETE {{base}}/86
Authorization: {{token}}