@base=http://localhost:3000/api
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjpudWxsLCJpYXQiOjE3NjkwNDcxNjZ9.h3_1elht79kXMtfET87wvq-NGU30H_1fDJ75g4PR1XU
### user list
GET {{base}}/user
Authorization: Bearer {{token}}

### user register           done
POST {{base}}/user/register
Content-Type: application/json

{
    "username": "123456",
    "password": "123456",
    "email": "123456@qq.com"
}

### user login             done
POST {{base}}/user/login
Content-Type: application/json

{
    "password": "123456",
    "email": "123456@qq.com"
}


### user list
GET {{base}}/user
Authorization: Bearer {{token}}

### user info
GET {{base}}/user/info
Authorization: Bearer {{token}}

### user update
PUT {{base}}/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username": "1234567890"
}

### user avatar
POST {{base}}/avatar
Authorization: Bearer {{token}}

### user avatar
POST {{base}}/user/avatar
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

avatar
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ./user.http
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### user info
GET {{base}}/user/1
Authorization: Bearer {{token}}

### user current
GET {{base}}/user/current
Authorization: Bearer {{token}}