@base=http://localhost:3000/api
### user list
POST {{base}}/util/sendEmailVerificationCode
Content-Type: application/json

{
    "email": "aachen2012@outlook.com"
}

### TEST
GET http://localhost:3000