services:
  server:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "4000:4000"
    expose:
      - "4000"
    env_file:
      - ../.env.devDocker
    volumes:
      - /var/log/docker-study:/app/logs:rw
    networks:
      - mac_docker_network
      - default

networks:
  mac_docker_network:
    external: true
