services:
  nginx:
    build:
      context: ../nginx
      args:
        NGINX_SITE: prod
    volumes:
      - ../nginx/html/dist:/usr/share/nginx/html:ro
      - ../nginx/ssl:/etc/ssl/cert:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server

  server:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    expose:
      - "4000"
    env_file:
      - ../.env.prod
    depends_on:
      redis:
        condition: service_started
    volumes:
      - /var/log/docker-study:/app/logs:rw
    networks:
      - mac_docker_network

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    command:
      ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]
    volumes:
      - redis_data_prod:/data

volumes:
  mysql_data_prod:
  redis_data_prod:

networks:
  mac_docker_network:
    external: true
