services:
  server:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "4000:4000"
    expose:
      - "4000"
    env_file:
      - ../.env.dev
    depends_on:
      redis:
        condition: service_started
    volumes:
      - /var/log/docker-study:/app/logs:rw
    networks:
      - mac_docker_network

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    command:
      ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]
    volumes:
      - redis_data_prod:/data
    networks:
      - mac_docker_network

volumes:
  redis_data_prod:

networks:
  mac_docker_network:
    external: true
