-- AlterTable
ALTER TABLE `ProductJoinSku` ADD COLUMN `balance` SMALLINT UNSIGNED NULL DEFAULT 0,
    ADD COLUMN `stockInPending` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN `stockOutPending` SMALLINT UNSIGNED NOT NULL DEFAULT 0;
